root:
  true
extends:
  - '@nuxtjs/eslint-config-typescript'
rules:
  quotes:
  - 'warn'
  - 'single'
  comma-dangle:
  - 'warn'
  - 'always-multiline'
  no-console: 'warn'
  no-unused-vars: 'warn'
  '@typescript-eslint/no-unused-vars': 'off'
  vue/no-unused-vars: 'off'
  require-await: 'warn'
  no-unreachable: 'warn'
  vue/no-v-model-argument: 'off'
  vue/no-v-for-template-key: 'off'
